name: macOS
permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install build tools
      run: brew install automake autoconf libtool pkg-config gettext

    - name: Install other dependencies
      run: |
        brew install libevent

    - name: Configure
      run: |
        export CFLAGS="-I$(brew --prefix)/include"
        export LDFLAGS="-L$(brew --prefix)/lib"
        autoreconf -fi
        ./configure --enable-daemon --enable-tests

    - name: Build
      run: |
        make
        make check

    - name: Test run
      run: |
        sudo ./daemon/airptpd
        ./tests/client
        sudo killall airptpd
